// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PurrfectShot.Web.Data;

#nullable disable

namespace PurrfectShot.Web.Migrations
{
    [DbContext(typeof(PurrfectShotDbContext))]
    [Migration("20260207174458_UpdateHoneyName")]
    partial class UpdateHoneyName
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.23")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PurrfectShot.Web.Models.Cat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Breed")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasComment("Indicates if the cat is still an active member of the household gallery.");

                    b.Property<int?>("MainPhotoId")
                        .HasColumnType("int")
                        .HasComment("The ID of the photo selected as the main profile picture for the cat.");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("MainPhotoId");

                    b.ToTable("Cats");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Breed = "Tuxedo Cat",
                            Description = "Сладък, мил и добричък. Най-добрият котко-татко",
                            IsActive = true,
                            Name = "Сър Мортимър"
                        },
                        new
                        {
                            Id = 2,
                            Breed = "Европейска Късокосместа",
                            Description = "Най-сладката рижа маца. Най-лесно определена като котка с характер",
                            IsActive = true,
                            Name = "Лейди Фрайни"
                        },
                        new
                        {
                            Id = 3,
                            Breed = "Египетска Мау",
                            Description = "Отговаря на името си, най-бързият скокльо-котарак. Обича да води дълги и пълноценни разговори",
                            IsActive = true,
                            Name = "Венти"
                        },
                        new
                        {
                            Id = 4,
                            Breed = "Европейска Късокосместа",
                            Description = "Най-малкото ни вече не-бебе коте, модел Морти. Позната като Хъни-Бъни",
                            IsActive = true,
                            Name = "Хъни-Бъни"
                        });
                });

            modelBuilder.Entity("PurrfectShot.Web.Models.Photo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Caption")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("CatId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateUploaded")
                        .HasColumnType("datetime2");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("CatId");

                    b.ToTable("Photos");
                });

            modelBuilder.Entity("PurrfectShot.Web.Models.Vote", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("PhotoId")
                        .HasColumnType("int");

                    b.Property<int>("Stars")
                        .HasColumnType("int");

                    b.Property<string>("VoterName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("PhotoId");

                    b.ToTable("Votes");
                });

            modelBuilder.Entity("PurrfectShot.Web.Models.Cat", b =>
                {
                    b.HasOne("PurrfectShot.Web.Models.Photo", "MainPhoto")
                        .WithMany()
                        .HasForeignKey("MainPhotoId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("MainPhoto");
                });

            modelBuilder.Entity("PurrfectShot.Web.Models.Photo", b =>
                {
                    b.HasOne("PurrfectShot.Web.Models.Cat", "Cat")
                        .WithMany("Photos")
                        .HasForeignKey("CatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cat");
                });

            modelBuilder.Entity("PurrfectShot.Web.Models.Vote", b =>
                {
                    b.HasOne("PurrfectShot.Web.Models.Photo", "Photo")
                        .WithMany("Votes")
                        .HasForeignKey("PhotoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Photo");
                });

            modelBuilder.Entity("PurrfectShot.Web.Models.Cat", b =>
                {
                    b.Navigation("Photos");
                });

            modelBuilder.Entity("PurrfectShot.Web.Models.Photo", b =>
                {
                    b.Navigation("Votes");
                });
#pragma warning restore 612, 618
        }
    }
}
