// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PurrfectShot.Web.Data;

#nullable disable

namespace PurrfectShot.Web.Migrations
{
    [DbContext(typeof(PurrfectShotDbContext))]
    [Migration("20260208162145_UpdateEntitiesWithComments")]
    partial class UpdateEntitiesWithComments
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.23")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PurrfectShot.Web.Models.Cat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasComment("Unique identifier for the cat.");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Breed")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasComment("The specific breed of the cat.");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasComment("A short biography or description of the cat's personality.");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasComment("Flag indicating if the cat is active or archived (soft-deleted).");

                    b.Property<Guid?>("MainPhotoId")
                        .HasColumnType("uniqueidentifier")
                        .HasComment("The unique identifier of the photo chosen as the cat's profile picture.");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasComment("The name of the cat.");

                    b.HasKey("Id");

                    b.HasIndex("MainPhotoId");

                    b.ToTable("Cats", t =>
                        {
                            t.HasComment("Represents a cat housemate in the system.");
                        });

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Breed = "Tuxedo Cat",
                            Description = "Сладък, мил и добричък. Най-добрият котко-татко",
                            IsActive = true,
                            Name = "Сър Мортимър"
                        },
                        new
                        {
                            Id = 2,
                            Breed = "Европейска Късокосместа",
                            Description = "Най-сладката рижа маца. Най-лесно определена като котка с характер",
                            IsActive = true,
                            Name = "Лейди Фрайни"
                        },
                        new
                        {
                            Id = 3,
                            Breed = "Египетска Мау",
                            Description = "Отговаря на името си, най-бързият скокльо-котарак. Обича да води дълги и пълноценни разговори",
                            IsActive = true,
                            Name = "Венти"
                        },
                        new
                        {
                            Id = 4,
                            Breed = "Европейска Късокосместа",
                            Description = "Най-малкото ни вече не-бебе коте, модел Морти. Позната като Хъни-Бъни",
                            IsActive = true,
                            Name = "Хъни-Бъни"
                        });
                });

            modelBuilder.Entity("PurrfectShot.Web.Models.Photo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasComment("Unique identifier for the photo entry.");

                    b.Property<string>("Caption")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasComment("A descriptive text or story accompanying the photo.");

                    b.Property<int>("CatId")
                        .HasColumnType("int")
                        .HasComment("Foreign key referencing the cat shown in the photo.");

                    b.Property<DateTime>("DateUploaded")
                        .HasColumnType("datetime2")
                        .HasComment("The exact date and time when the photo was uploaded.");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasComment("The relative server path where the physical image file is stored.");

                    b.HasKey("Id");

                    b.HasIndex("CatId");

                    b.HasIndex("DateUploaded");

                    b.ToTable("Photos", t =>
                        {
                            t.HasComment("Represents an uploaded image of a cat.");
                        });

                    b.HasData(
                        new
                        {
                            Id = new Guid("f1085f28-5def-45a8-9f6b-64287e8c5413"),
                            Caption = "Ами ако никога не мърдна от тук?",
                            CatId = 1,
                            DateUploaded = new DateTime(2026, 1, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FilePath = "/images/seed/SirMortiPhoto_1.jpg"
                        },
                        new
                        {
                            Id = new Guid("7592715c-1d9a-4848-8c4d-2194fe0f477c"),
                            Caption = "Слийпи блем",
                            CatId = 1,
                            DateUploaded = new DateTime(2026, 3, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FilePath = "/images/seed/SirMortiPhoto_2.jpg"
                        },
                        new
                        {
                            Id = new Guid("bb536fa6-7323-42ac-99d3-971e1e9587ae"),
                            Caption = "Лордът на слънчевите бани",
                            CatId = 1,
                            DateUploaded = new DateTime(2026, 1, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FilePath = "/images/seed/SirMortiPhoto_3.jpg"
                        },
                        new
                        {
                            Id = new Guid("f86bfb53-eb39-4770-94f5-35a4710d037f"),
                            Caption = "Гледаме си от пенхауса",
                            CatId = 1,
                            DateUploaded = new DateTime(2026, 4, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FilePath = "/images/seed/SirMortiPhoto_4.jpg"
                        },
                        new
                        {
                            Id = new Guid("ffdb1b39-5ee0-471b-b666-f88e210ec99c"),
                            Caption = "Заспал блем в котешкото легло",
                            CatId = 1,
                            DateUploaded = new DateTime(2026, 2, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FilePath = "/images/seed/SirMortiPhoto_5.jpg"
                        },
                        new
                        {
                            Id = new Guid("7ed1f628-46ce-4fb8-9295-d93e976f0116"),
                            Caption = "Отново... спим",
                            CatId = 1,
                            DateUploaded = new DateTime(2026, 7, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FilePath = "/images/seed/SirMortiPhoto_6.jpg"
                        },
                        new
                        {
                            Id = new Guid("256e3cf7-f9ec-4f14-8361-e2e6fd2ce0e4"),
                            Caption = "Морти и неговата кашоно-къща",
                            CatId = 1,
                            DateUploaded = new DateTime(2026, 1, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FilePath = "/images/seed/SirMortiPhoto_7.jpg"
                        },
                        new
                        {
                            Id = new Guid("769bd5cb-e50b-46b5-875c-51ace4382828"),
                            Caption = "Дай *прозявка* пет",
                            CatId = 1,
                            DateUploaded = new DateTime(2026, 6, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FilePath = "/images/seed/SirMortiPhoto_8.jpg"
                        },
                        new
                        {
                            Id = new Guid("40c09f56-f0c0-46e1-9c48-461458c3bbb0"),
                            Caption = "Когато си най-сладката писанка на света",
                            CatId = 2,
                            DateUploaded = new DateTime(2026, 1, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FilePath = "/images/seed/LadyPhrynePhoto_1.jpg"
                        },
                        new
                        {
                            Id = new Guid("4b7702ad-a3f7-4169-8e82-ebe4865b8953"),
                            Caption = "Размисли над живота от новото си легло",
                            CatId = 2,
                            DateUploaded = new DateTime(2026, 2, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FilePath = "/images/seed/LadyPhrynePhoto_2.jpg"
                        },
                        new
                        {
                            Id = new Guid("3f1d8d99-c8e4-4768-8f0c-caac648ad543"),
                            Caption = "..или просто прозявка",
                            CatId = 2,
                            DateUploaded = new DateTime(2026, 2, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FilePath = "/images/seed/LadyPhrynePhoto_3.jpg"
                        },
                        new
                        {
                            Id = new Guid("80377db9-ed3a-4013-b325-64651c2a4b6c"),
                            Caption = "В пастта на акулата",
                            CatId = 2,
                            DateUploaded = new DateTime(2026, 6, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FilePath = "/images/seed/LadyPhrynePhoto_4.jpg"
                        },
                        new
                        {
                            Id = new Guid("7db14ae0-d116-41ee-82db-a5d7abceee2a"),
                            Caption = "Две котки, една перална",
                            CatId = 2,
                            DateUploaded = new DateTime(2026, 7, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FilePath = "/images/seed/LadyPhrynePhoto_5.jpg"
                        },
                        new
                        {
                            Id = new Guid("861ea7f6-af4e-4b67-96ff-61c6abe2fa0d"),
                            Caption = "Не само щраусите могат така",
                            CatId = 2,
                            DateUploaded = new DateTime(2026, 2, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FilePath = "/images/seed/LadyPhrynePhoto_6.jpg"
                        },
                        new
                        {
                            Id = new Guid("864f6ad7-4eba-4848-83ed-a7eec7fe15e6"),
                            Caption = "А ти какво гледаш?",
                            CatId = 2,
                            DateUploaded = new DateTime(2026, 1, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FilePath = "/images/seed/LadyPhrynePhoto_7.jpg"
                        },
                        new
                        {
                            Id = new Guid("2332efed-2870-427f-aefd-dbfd8bb14043"),
                            Caption = "Лейди Фрайни, върху трупът на лисицата",
                            CatId = 2,
                            DateUploaded = new DateTime(2026, 2, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FilePath = "/images/seed/LadyPhrynePhoto_8.jpg"
                        },
                        new
                        {
                            Id = new Guid("dbf3cd30-3b4b-483d-80ff-ef12a3eead94"),
                            Caption = "Тунелни истории",
                            CatId = 2,
                            DateUploaded = new DateTime(2026, 8, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FilePath = "/images/seed/LadyPhrynePhoto_9.jpg"
                        },
                        new
                        {
                            Id = new Guid("42174d8b-9db8-4098-9f38-371005220780"),
                            Caption = "Венти - най-бързият селфи-майстор",
                            CatId = 3,
                            DateUploaded = new DateTime(2026, 1, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FilePath = "/images/seed/VentiPhoto_1.jpg"
                        },
                        new
                        {
                            Id = new Guid("89bae15d-1c8e-4299-80ff-9c14578ab6ee"),
                            Caption = "Ето така се мият котешките лапи",
                            CatId = 3,
                            DateUploaded = new DateTime(2026, 2, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FilePath = "/images/seed/VentiPhoto_2.jpg"
                        },
                        new
                        {
                            Id = new Guid("b3dff3d3-0115-4ac5-9cd9-192c5f059109"),
                            Caption = "Снейк кат",
                            CatId = 3,
                            DateUploaded = new DateTime(2026, 10, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FilePath = "/images/seed/VentiPhoto_3.jpg"
                        },
                        new
                        {
                            Id = new Guid("0aca87fc-58b9-483b-b80e-74a811811372"),
                            Caption = "Диванът не е достатъчно голям",
                            CatId = 3,
                            DateUploaded = new DateTime(2026, 2, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FilePath = "/images/seed/VentiPhoto_4.jpg"
                        },
                        new
                        {
                            Id = new Guid("3360a037-aa1d-4bf5-b04b-da6afac92599"),
                            Caption = "Vent do you want?",
                            CatId = 3,
                            DateUploaded = new DateTime(2026, 12, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FilePath = "/images/seed/VentiPhoto_5.jpg"
                        },
                        new
                        {
                            Id = new Guid("be283f19-0b3c-4adb-b235-e4b64d247db4"),
                            Caption = "Най-добре е върху лапата на папа",
                            CatId = 3,
                            DateUploaded = new DateTime(2026, 1, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FilePath = "/images/seed/VentiPhoto_6.jpg"
                        },
                        new
                        {
                            Id = new Guid("ac07d5d6-c099-45e9-b725-f09ad314e9d3"),
                            Caption = "Малко блем и карти",
                            CatId = 3,
                            DateUploaded = new DateTime(2026, 2, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FilePath = "/images/seed/VentiPhoto_7.jpg"
                        },
                        new
                        {
                            Id = new Guid("38058665-8726-41fa-be91-41de9acd0f72"),
                            Caption = "Не, всъщност, ето така се мият котешки лапи",
                            CatId = 3,
                            DateUploaded = new DateTime(2026, 1, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FilePath = "/images/seed/VentiPhoto_8.jpg"
                        },
                        new
                        {
                            Id = new Guid("7f2e351c-6c8e-4261-ae66-b29bded5298d"),
                            Caption = "It's just me and my cat bed",
                            CatId = 3,
                            DateUploaded = new DateTime(2026, 2, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FilePath = "/images/seed/VentiPhoto_9.jpg"
                        },
                        new
                        {
                            Id = new Guid("5e14f8a8-6bd3-41d1-aca1-0d8f052d9241"),
                            Caption = "Венти, йога-котка",
                            CatId = 3,
                            DateUploaded = new DateTime(2026, 11, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FilePath = "/images/seed/VentiPhoto_10.jpg"
                        },
                        new
                        {
                            Id = new Guid("9940e6f5-8edd-4e94-ad94-89579118a578"),
                            Caption = "Хъни-Бъни и нейната аура на сладост",
                            CatId = 4,
                            DateUploaded = new DateTime(2026, 11, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FilePath = "/images/seed/HoneyBuneyPhoto_1.jpg"
                        },
                        new
                        {
                            Id = new Guid("b79cb330-da37-4a09-8eaf-bfde8951051f"),
                            Caption = "Заспали и завити с на мама дрехите",
                            CatId = 4,
                            DateUploaded = new DateTime(2026, 11, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FilePath = "/images/seed/HoneyBuneyPhoto_2.jpg"
                        },
                        new
                        {
                            Id = new Guid("f62689fd-0798-4eb7-a0de-d9dc98f9b1fd"),
                            Caption = "Когато се миеш на трона",
                            CatId = 4,
                            DateUploaded = new DateTime(2026, 12, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FilePath = "/images/seed/HoneyBuneyPhoto_3.jpg"
                        },
                        new
                        {
                            Id = new Guid("dcf0db9d-886f-40b1-9078-09cb80973b3a"),
                            Caption = "Дебнейки от стола",
                            CatId = 4,
                            DateUploaded = new DateTime(2026, 2, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FilePath = "/images/seed/HoneyBuneyPhoto_4.jpg"
                        },
                        new
                        {
                            Id = new Guid("0c74aadc-266b-47cd-9c56-995b73324753"),
                            Caption = "Honey Bunny means business",
                            CatId = 4,
                            DateUploaded = new DateTime(2026, 2, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FilePath = "/images/seed/HoneyBuneyPhoto_5.jpg"
                        },
                        new
                        {
                            Id = new Guid("fb6ca040-2d9c-4793-9d75-17fb6cca6ae4"),
                            Caption = "Облизваме се на стола на папа",
                            CatId = 4,
                            DateUploaded = new DateTime(2026, 3, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FilePath = "/images/seed/HoneyBuneyPhoto_6.jpg"
                        },
                        new
                        {
                            Id = new Guid("59392be0-f7de-4bcd-84b2-99f19a341503"),
                            Caption = "Папа, защо батко ме мие?",
                            CatId = 4,
                            DateUploaded = new DateTime(2026, 2, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FilePath = "/images/seed/HoneyBuneyPhoto_7.jpg"
                        },
                        new
                        {
                            Id = new Guid("3c164cdb-459f-4c9b-947d-60dc957085fe"),
                            Caption = "*музика от Цар Лъв*",
                            CatId = 4,
                            DateUploaded = new DateTime(2026, 7, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FilePath = "/images/seed/HoneyBuneyPhoto_8.jpg"
                        },
                        new
                        {
                            Id = new Guid("0b0ede57-0b57-4ba2-abac-bb9468aca00c"),
                            Caption = "Знам, че той ме гледа",
                            CatId = 4,
                            DateUploaded = new DateTime(2026, 2, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FilePath = "/images/seed/HoneyBuneyPhoto_9.jpg"
                        });
                });

            modelBuilder.Entity("PurrfectShot.Web.Models.Vote", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasComment("Unique identifier for the vote entry.");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<Guid>("PhotoId")
                        .HasColumnType("uniqueidentifier")
                        .HasComment("Foreign key referencing the rated photo.");

                    b.Property<int>("Stars")
                        .HasColumnType("int")
                        .HasComment("The number of stars awarded (from 1 to 5).");

                    b.Property<string>("VoterName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasComment("The name of the user who cast the vote.");

                    b.HasKey("Id");

                    b.HasIndex("PhotoId");

                    b.ToTable("Votes", t =>
                        {
                            t.HasComment("Represents a single rating given to a photo.");
                        });
                });

            modelBuilder.Entity("PurrfectShot.Web.Models.Cat", b =>
                {
                    b.HasOne("PurrfectShot.Web.Models.Photo", "MainPhoto")
                        .WithMany()
                        .HasForeignKey("MainPhotoId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("MainPhoto");
                });

            modelBuilder.Entity("PurrfectShot.Web.Models.Photo", b =>
                {
                    b.HasOne("PurrfectShot.Web.Models.Cat", "Cat")
                        .WithMany("Photos")
                        .HasForeignKey("CatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cat");
                });

            modelBuilder.Entity("PurrfectShot.Web.Models.Vote", b =>
                {
                    b.HasOne("PurrfectShot.Web.Models.Photo", "Photo")
                        .WithMany("Votes")
                        .HasForeignKey("PhotoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Photo");
                });

            modelBuilder.Entity("PurrfectShot.Web.Models.Cat", b =>
                {
                    b.Navigation("Photos");
                });

            modelBuilder.Entity("PurrfectShot.Web.Models.Photo", b =>
                {
                    b.Navigation("Votes");
                });
#pragma warning restore 612, 618
        }
    }
}
